In [1]:
import pandas as pd

### Q1. Pandas version

In [2]:
pd.__version__

'2.2.2'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-22 00:54:01--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.03s   

2024-09-22 00:54:02 (10.9 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [4]:
df = pd.read_csv('laptops.csv')

### Q2. Records count
### How many records are in the dataset?

In [68]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [54]:
2160

2160

### Q3. Laptop brands
### How many laptop brands are presented in the dataset?

In [72]:
df.Brand.describe()

count     2160
unique      27
top       Asus
freq       415
Name: Brand, dtype: object

In [55]:
27

27

### Q4. Missing values
### How many columns in the dataset have missing values?

In [69]:
df.isnull().sum()[df.isnull().sum()>0]

Storage type      42
GPU             1371
Screen             4
dtype: int64

In [56]:
3

3

### Q5. Maximum final price
### What's the maximum final price of Dell notebooks in the dataset?

In [57]:
# To check how Dell name is stored in the dataframe
df.Brand.unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [58]:
df[df.Brand == 'Dell']['Final Price'].max()

np.float64(3936.0)

### Q6. Median value of Screen
### Median value of Screen
#### Find the median value of Screen column in the dataset.
#### Next, calculate the most frequent value of the same Screen column.
#### Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
#### Now, calculate the median value of Screen once again.
#### Has it changed?

In [25]:
df.Screen.median()

np.float64(15.6)

In [27]:
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

In [28]:
df.Screen.fillna(df.Screen.mode(),inplace=True)

In [29]:
df.Screen.median()

np.float64(15.6)

In [60]:
### Not Changed

### Q7. Sum of weights
#### Select all the "Innjoo" laptops from the dataset.
#### Select only columns RAM, Storage, Screen.
#### Get the underlying NumPy array. Let's call it X.
#### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#### Compute the inverse of XTX.
#### Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#### What's the sum of all the elements of the result?

In [36]:
df[df.Brand == 'Innjoo'][['RAM','Storage','Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [37]:
import numpy as np

In [39]:
X = np.array(df[df.Brand == 'Innjoo'][['RAM','Storage','Screen']])

In [41]:
X.shape

(6, 3)

In [61]:
### Shape 3x6 * 6x3 = 3x3

In [43]:
X.T.dot(X)

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [44]:
XTX = X.T.dot(X)

In [64]:
### Applying the inverse

In [47]:
XTXI = np.linalg.inv(XTX)

In [48]:
XTXI

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [46]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [65]:
XTXI.dot(X.T)

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [66]:
XTXI.dot(X.T).shape

(3, 6)

In [ ]:
### Shape 3x6 * 6x1 = 3x1

In [51]:
w = XTXI.dot(X.T).dot(y)

In [67]:
w.shape

(3,)

In [53]:
w.sum()

np.float64(91.2998806299555)